### ISSUE TITLE
Help getting this code running

### ISSUE THREAD

**Issue by bumper314** [s9w/Ginseng#1]
I would like to see Ginseng in action, but eatginseng.com is unregistered and webarchive.org can't seem to load any of the old snapshots.

So I'm trying to build the app myself, but there seems to be some missing files:
- diff.js
- lz-string.min.js
- tex2jax.js

Ran `make`, but I'm unfamiliar with `browserify` and haven't been able to resolve what seems like a simple error:

```
$ make
browserify jsx/Ginseng.jsx -t babelify --outfile js/ginseng.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'js/ginseng.js.tmp-browserify-41120465702890940385'
make: *** [js/ginseng.js] Error 1
```

I can't find `events.js` or where it's even being referenced from.

Any hints would be appreciated.

**Comment by s9w** [comment]
Hey! Now this is a surprise. During its lifetime, Ginseng didn't have many users. I ultimately axed the project because web technologies are insane. Breaking updates for React were coming every couple of weeks, and it took more time to make all the tech working than working on the project itself. So it's no longer developed, maintained or even used. Browserify is one of the myriad of magic programs that people use to make js actually usable. I'm sure that current versions are in no way compatible to my code (yeah I'm kinda ranting :D). If you really want to, you could still use it I guess. But the easier way is just using Anki.

Ginseng might get a revival, but that would probably be with non-web technologies like a Qt Program.

**Comment by bumper314** [comment]
Thanks for the reply.  As a long time Mac developer, I can commiserate and long for the golden days of stable APIs and toolchains on an OS with a 3+ year development cycle, rather than yearly.  Any time I try to touch my older apps, I spend a few hours fighting with Xcode and certificates before giving up.  The best option I found is to build my dev environments in virtual machines, locked to a specific OS version and set of tools that I know work, but that just abstracts the problem one level to where I have to maintain dozens of VMs taking up terabytes of space.  Pick your poison I guess.
